# Generated by Django 2.2.5 on 2020-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200811_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='faciliies',
            new_name='facilities',
        ),
    ]
